---
- name: Ensure local path exists
  ansible.builtin.file:
    path: /tmp/app
    state: directory
  delegate_to: localhost
  become: false

- name: Clone app web respo
  ansible.builtin.git:
    repo: https://github.com/ByJeanCa/ByJeanCa-ByJeanCa-CI-CD-with-Jenkins-Ansible-and-S3-on-EC2
    dest: "{{ local_files }}"
    version: main
  delegate_to: localhost
  become: false